//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.16 at 12:03:14 PM CET 
//


package es.safcce.comun.util.bean.datosfirmaxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DatosFirmante complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatosFirmante">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NombreApellidosRazonSocial" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Pais" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TipoDocumento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NumIdentificacion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NavegadorIP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NavegadorUserAgent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatosFirmante", propOrder = {
    "nombreApellidosRazonSocial",
    "pais",
    "tipoDocumento",
    "numIdentificacion",
    "navegadorIP",
    "navegadorUserAgent"
})
public class DatosFirmante {

    @XmlElement(name = "NombreApellidosRazonSocial", required = true)
    protected String nombreApellidosRazonSocial;
    @XmlElement(name = "Pais", required = true)
    protected String pais;
    @XmlElement(name = "TipoDocumento", required = true)
    protected String tipoDocumento;
    @XmlElement(name = "NumIdentificacion", required = true)
    protected String numIdentificacion;
    @XmlElement(name = "NavegadorIP", required = true)
    protected String navegadorIP;
    @XmlElement(name = "NavegadorUserAgent", required = true)
    protected String navegadorUserAgent;

    /**
     * Gets the value of the nombreApellidosRazonSocial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreApellidosRazonSocial() {
        return nombreApellidosRazonSocial;
    }

    /**
     * Sets the value of the nombreApellidosRazonSocial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreApellidosRazonSocial(String value) {
        this.nombreApellidosRazonSocial = value;
    }

    /**
     * Gets the value of the pais property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPais() {
        return pais;
    }

    /**
     * Sets the value of the pais property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPais(String value) {
        this.pais = value;
    }

    /**
     * Gets the value of the tipoDocumento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoDocumento() {
        return tipoDocumento;
    }

    /**
     * Sets the value of the tipoDocumento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoDocumento(String value) {
        this.tipoDocumento = value;
    }

    /**
     * Gets the value of the numIdentificacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumIdentificacion() {
        return numIdentificacion;
    }

    /**
     * Sets the value of the numIdentificacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumIdentificacion(String value) {
        this.numIdentificacion = value;
    }

    /**
     * Gets the value of the navegadorIP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNavegadorIP() {
        return navegadorIP;
    }

    /**
     * Sets the value of the navegadorIP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNavegadorIP(String value) {
        this.navegadorIP = value;
    }

    /**
     * Gets the value of the navegadorUserAgent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNavegadorUserAgent() {
        return navegadorUserAgent;
    }

    /**
     * Sets the value of the navegadorUserAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNavegadorUserAgent(String value) {
        this.navegadorUserAgent = value;
    }

}
