//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.16 at 12:03:14 PM CET 
//


package es.safcce.comun.util.bean.datosfirmaxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DatosFirma complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatosFirma">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TimeStampFirma" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="HuellaFirma" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NombreDocumento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HashDocumento" type="{safcceFirma}HashDocumento"/>
 *         &lt;element name="Resultado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatosFirma", propOrder = {
    "timeStampFirma",
    "huellaFirma",
    "nombreDocumento",
    "hashDocumento",
    "resultado"
})
public class DatosFirma {

    @XmlElement(name = "TimeStampFirma", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeStampFirma;
    @XmlElement(name = "HuellaFirma", required = true)
    protected String huellaFirma;
    @XmlElement(name = "NombreDocumento", required = true)
    protected String nombreDocumento;
    @XmlElement(name = "HashDocumento", required = true)
    protected HashDocumento hashDocumento;
    @XmlElement(name = "Resultado", required = true)
    protected String resultado;

    /**
     * Gets the value of the timeStampFirma property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeStampFirma() {
        return timeStampFirma;
    }

    /**
     * Sets the value of the timeStampFirma property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeStampFirma(XMLGregorianCalendar value) {
        this.timeStampFirma = value;
    }

    /**
     * Gets the value of the huellaFirma property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHuellaFirma() {
        return huellaFirma;
    }

    /**
     * Sets the value of the huellaFirma property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHuellaFirma(String value) {
        this.huellaFirma = value;
    }

    /**
     * Gets the value of the nombreDocumento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreDocumento() {
        return nombreDocumento;
    }

    /**
     * Sets the value of the nombreDocumento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreDocumento(String value) {
        this.nombreDocumento = value;
    }

    /**
     * Gets the value of the hashDocumento property.
     * 
     * @return
     *     possible object is
     *     {@link HashDocumento }
     *     
     */
    public HashDocumento getHashDocumento() {
        return hashDocumento;
    }

    /**
     * Sets the value of the hashDocumento property.
     * 
     * @param value
     *     allowed object is
     *     {@link HashDocumento }
     *     
     */
    public void setHashDocumento(HashDocumento value) {
        this.hashDocumento = value;
    }

    /**
     * Gets the value of the resultado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultado() {
        return resultado;
    }

    /**
     * Sets the value of the resultado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultado(String value) {
        this.resultado = value;
    }

}
