//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.16 at 12:03:14 PM CET 
//


package es.safcce.comun.util.bean.datosfirmaxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SPId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SPCodigoTramite" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SPNivelSeguridadQAA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TimeStampAutenticacion" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="DatosFirma" type="{safcceFirma}DatosFirma"/>
 *         &lt;element name="DatosFirmante" type="{safcceFirma}DatosFirmante"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "spId",
    "spCodigoTramite",
    "spNivelSeguridadQAA",
    "timeStampAutenticacion",
    "datosFirma",
    "datosFirmante"
})
@XmlRootElement(name = "Firma")
public class Firma {

    @XmlElement(name = "SPId", required = true)
    protected String spId;
    @XmlElement(name = "SPCodigoTramite", required = true)
    protected String spCodigoTramite;
    @XmlElement(name = "SPNivelSeguridadQAA", required = true)
    protected String spNivelSeguridadQAA;
    @XmlElement(name = "TimeStampAutenticacion", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeStampAutenticacion;
    @XmlElement(name = "DatosFirma", required = true)
    protected DatosFirma datosFirma;
    @XmlElement(name = "DatosFirmante", required = true)
    protected DatosFirmante datosFirmante;

    /**
     * Gets the value of the spId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPId() {
        return spId;
    }

    /**
     * Sets the value of the spId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPId(String value) {
        this.spId = value;
    }

    /**
     * Gets the value of the spCodigoTramite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPCodigoTramite() {
        return spCodigoTramite;
    }

    /**
     * Sets the value of the spCodigoTramite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPCodigoTramite(String value) {
        this.spCodigoTramite = value;
    }

    /**
     * Gets the value of the spNivelSeguridadQAA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPNivelSeguridadQAA() {
        return spNivelSeguridadQAA;
    }

    /**
     * Sets the value of the spNivelSeguridadQAA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPNivelSeguridadQAA(String value) {
        this.spNivelSeguridadQAA = value;
    }

    /**
     * Gets the value of the timeStampAutenticacion property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeStampAutenticacion() {
        return timeStampAutenticacion;
    }

    /**
     * Sets the value of the timeStampAutenticacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeStampAutenticacion(XMLGregorianCalendar value) {
        this.timeStampAutenticacion = value;
    }

    /**
     * Gets the value of the datosFirma property.
     * 
     * @return
     *     possible object is
     *     {@link DatosFirma }
     *     
     */
    public DatosFirma getDatosFirma() {
        return datosFirma;
    }

    /**
     * Sets the value of the datosFirma property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatosFirma }
     *     
     */
    public void setDatosFirma(DatosFirma value) {
        this.datosFirma = value;
    }

    /**
     * Gets the value of the datosFirmante property.
     * 
     * @return
     *     possible object is
     *     {@link DatosFirmante }
     *     
     */
    public DatosFirmante getDatosFirmante() {
        return datosFirmante;
    }

    /**
     * Sets the value of the datosFirmante property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatosFirmante }
     *     
     */
    public void setDatosFirmante(DatosFirmante value) {
        this.datosFirmante = value;
    }

}
